administrative/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'administrative.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('leave.urls'))	#Redirect everything to Leave App

)

leave/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

from leave import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),  
    url(r'^dept/$', views.dept, name='dept'),
    url(r'^new/([a-zA-Z]+)?$', views.new_application, name='new_application'),
    url(r'^history/([a-zA-Z]+)?/?([0-9]{4})?-?([0-9]{2})?-?([0-9]{2})?', views.sent, name='sent'),
    url(r'^applications/([a-zA-Z]+)?/?([0-9]{4})?-?([0-9]{2})?-?([0-9]{2})?', views.applications,name='applications'),
    url(r'^logt/',views.logt,name='logt'),
    url(r'^application/(\d+)/print$',views.print_application,name='print'),
    url(r'^action/(\d+)/print$',views.print_action,name='print_action'),
    url(r'^application/(\d+)/cancel$',views.cancel,name='cancel'),
    url(r'^action/(\d+)/$',views.action,name='action'),
    url(r'^actions/([a-zA-Z]+)?$',views.actions,name='actions'),
    url(r'^manage_action/$',views.manage_action,name='manage_action'),
    url(r'^action_history/([a-zA-Z]+)?$',views.action_history,name='action_history'),
    url(r'^employee/(\d+)/$',views.employee,name='employee'),
    url(r'^employees/$',views.employees,name='employees'),
    url(r'^select_employee/$',views.select_employee,name='select_employee'),
    url(r'^employee/(\d+)/edit$',views.edit_employee,name='edit_employee'),
    url(r'^employee/new$',views.new_employee,name='new_employee'),
    url(r'^application/(\d+)/$',views.details,name='details'),
    url(r'^manage_leave/$',views.manage_leave,name='manage_leave'),
    url(r'^delete_application/$',views.delete_application,name='delete_application'),
    url(r'^delete_action/$',views.delete_action,name='delete_action'),
    url(r'^start_processing/$',views.start_processing,name='start_processing'),
    url(r'^complete/$',views.complete,name='complete'),
    url(r'^user_guide/$', views.user_guide,name='user_guide'),
 	url(r'^attachments/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }))
 

leave/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from CustomFileField import CustomFileField

# Each choice in this list represents a End-User of the software,
# who has the previlege to enter a new application to the system.


#Types of leave
LEAVE_TYPES = (
	#(1,'Special Casual Leave'),
	(1,'Earned Leave'),
	(2,'Half Pay Leave'),
	(3,'Commuted Leave'),
	#(3,'On Duty Leave'),
	)



#Different types of users
USER_TYPES = (
	(0, ''),
	(1,	'Section Head'),
    (2, 'Est. Office'),
    (4, 'Deputy Registrar'),
    (5, 'Data Admin')
)


#Status of Application
STATUS = (
	(0,'Deleted'),
	(1,'Pending'),
	(2,'Processing'),
	(3,'Approved'),
	(4,'Rejected'),
	(5,'Cancelled')
	)

class Department(models.Model):
	name = models.CharField(max_length=100)
	def __unicode__(self):
		return self.name

#Model for employees
class Employee(models.Model):
		
	code = models.CharField(max_length=10,null=True,unique=True)
	name = models.CharField(max_length=100)
	dept = models.ForeignKey('Department')
	earned_balance = models.IntegerField(default=0)
	hp_balance = models.IntegerField(default=0)
	email = models.EmailField(max_length=75)
	is_active= models.BooleanField(default=False)

	def __unicode__(self):
		return self.code+" : "+self.name

	def isLeaveLeft(self,days,leave_type):
		if leave_type==1:
			return days<=self.earned_balance
		elif leave_type==2:
			return days<=self.hp_balance
		elif leave_type==3:
			return days*2<=self.hp_balance
		else:
			return False

	def approveTransaction(self,days,leave_type,action_type):
		earned_change=0
		hp_change=0
		if leave_type==1:
			earned_change+=days*action_type
		elif leave_type==2:
			hp_change+=days*action_type
		elif leave_type==3:
			hp_change+=2*days*action_type
		self.transaction(hp_change,earned_change);
		return True

	def transaction(self,hp_change,earned_change):
		self.earned_balance+=earned_change
		self.hp_balance+=hp_change
		self.save()
		return True

class EmployeeUpdateLog(models.Model):
	action=models.OneToOneField('Action',related_name='update_log')
	employee=models.ForeignKey('Employee')
	is_new=models.BooleanField(default=False)
	new_name = models.CharField(max_length=100)
	new_dept = models.ForeignKey('Department',related_name='update_new_dept')
	new_email = models.EmailField(max_length=75)
	new_is_active= models.BooleanField(default=True)
	old_name = models.CharField(max_length=100)
	old_dept = models.ForeignKey('Department',related_name='update_old_dept')
	old_email = models.EmailField(max_length=75)
	old_is_active= models.BooleanField(default=True)
	


#Model to represent different types of users 
class UserProfile(models.Model):

	user = models.OneToOneField(User)
	user_type = models.IntegerField(choices=USER_TYPES)
	dept = models.ForeignKey('Department')
	

class Action(models.Model):
	count=models.IntegerField(default=0)
	is_leave=models.BooleanField(default=True)
	note=models.TextField(max_length=100,blank=True,null=True)
	status=models.IntegerField(choices=STATUS,default=1)
	time_generated=models.DateTimeField(auto_now_add=True)
	time_approved=models.DateTimeField(null=True)
	reply_note=models.TextField(max_length=100,blank=True,null=True)

	def toText(self):
		if self.is_leave:
			return "Leave Credit/Debit"
		else:
			if self.update_log.is_new:
				return "Add New Employee"
			else:
				return "Edit Employee Details"

	

class ApplicationLog(models.Model):
	application=models.ForeignKey('Application')
	time = models.DateTimeField()
	activity= models.TextField(max_length=100,blank=True,null=True)
	notes=models.TextField(max_length=100,blank=True,null=True)


class TransactionLog(models.Model):
	employee=models.ForeignKey('Employee')
	action=models.ForeignKey('Action',null=True)
	application=models.ForeignKey('Application',null=True)
	is_admin=models.BooleanField(default=False)
	earned_balance=models.IntegerField()
	earned_change=models.IntegerField(default=0)
	hp_balance=models.IntegerField()
	hp_change=models.IntegerField(default=0)
	note=models.TextField(max_length=100,blank=True,null=True)
	time= models.DateTimeField(null=True)


	def toText(self):
		change=0
		text=""
		
		if self.hp_change:
			change=self.hp_change
			text+=str(abs(change))+" Halfpay leave "
		elif self.earned_change:
			change=self.earned_change
			text+=str(abs(change))+" Earned leave "

		if change<0:
			text+="Debit "
		elif change>0:
			text+="Credit "
		elif change==0:
			return "No changes in leave balance"

		return text

	def ApplicationTransaction(self,employee,application):
		earned_balance=employee.earned_balance
		hp_balance=employee.hp_balance
		earned_change=0
		hp_change=0
		if application.is_credit:
			if application.is_new:
				action_type=1
			else :
				action_type=-1
		else:
			if application.is_new:
				action_type=-1
			else :
				action_type=1

		if application.is_credit:
			days=application.days
		else:
			days=(application.new_date_to-application.new_date_from).days+1

		if application.leave_type==1:
			earned_change+=days*action_type
		elif application.leave_type==2:
			hp_change+=days*action_type
		elif application.leave_type==3:
			hp_change+=2*days*action_type
			

		self.employee=employee
		self.application=application
		self.earned_balance=earned_balance
		self.earned_change=earned_change
		self.hp_balance=hp_balance
		self.hp_change=hp_change
		self.time=datetime.now()
		self.save()

	def AdminTransaction(self,action,employee,leave_type,days,action_type,note):
		earned_balance=employee.earned_balance
		hp_balance=employee.hp_balance
		earned_change=0
		hp_change=0
		if leave_type==1:
			earned_change+=days*action_type
		elif leave_type==2:
			hp_change+=days*action_type
		elif leave_type==3:
			hp_change+=days*2*action_type
		self.action=action
		print action
		self.employee=employee
		self.leave_type=leave_type
		self.is_admin=True
		self.earned_balance=earned_balance
		self.earned_change=earned_change
		self.hp_balance=hp_balance
		self.hp_change=hp_change
		self.time=datetime.now()
		self.note=note
		self.save()
	
	



#Model to represent an individual application
class Application(models.Model):

	employee = models.ForeignKey('Employee')
	is_new = models.BooleanField(default=True)
	is_credit= models.BooleanField(default=False)
	original= models.ForeignKey('self',null=True)
	# Original field of New applications refers to ongoing cancel request for the same
	leave_type = models.IntegerField(choices=LEAVE_TYPES)
	date_from = models.DateField(null=True)
	date_to	= models.DateField(null=True)
	days=models.IntegerField(default=0)
	status = models.IntegerField(choices=STATUS,default=1)
	reason = models.TextField(max_length=200)
	new_date_to=models.DateField(null=True)
	new_date_from=models.DateField(null=True)
	attachment1= CustomFileField(upload_to='.',null=True,blank=True)
	attachment2= CustomFileField(upload_to='.',null=True,blank=True)
	attachment3= CustomFileField(upload_to='.',null=True,blank=True)
	time_generated = models.DateTimeField(auto_now_add=True)
	time_received = models.DateTimeField(null=True)
	time_approved = models.DateTimeField(null=True,blank=True)
	#This field will be set only when the application is approved/rejected	
	

	def __unicode__(self):
		return self.employee.name + " - " + self.get_leave_type_display()	

	def toText(self):
		text=""
		if self.is_new and not self.is_credit:
			text+="New "+self.get_leave_type_display()+" "
		elif self.is_new and self.is_credit:
			text+="Credit "+self.get_leave_type_display()+" "

		else:
			text+="Cancel Approved Leave"
		
		return text





	def CancelRequest(self,reason,attachment1,attachment2,attachment3):
		cancel_application=Application(original=self,is_new=False,
		employee=self.employee,leave_type=self.leave_type,date_from=self.new_date_from,
		date_to=self.new_date_to,new_date_from=self.new_date_from,
		new_date_to=self.new_date_to,reason=reason,attachment1=attachment1,
		attachment2=attachment2,attachment3=attachment3,)
		cancel_application.save()
		self.original=cancel_application
		# Original field of New applications refers to ongoing cancel request for the same
		self.save()
		return cancel_application
















	

leave/forms.py
from django import forms
from django.forms import ModelForm,Textarea,DateInput,save_instance

from datetime import datetime 
from leave.models import Application,Employee,Department
from django.forms.extras.widgets import SelectDateWidget
from CustomFileField import CustomFileField

class ApplicationForm(ModelForm):

	
	def __init__(self, dept,*args, **kwargs):
	    super(ApplicationForm, self).__init__(*args, **kwargs)
	    self.fields['attachment1'].label = "Attachment 1"
	    self.fields['attachment2'].label = "Attachment 2"
	    self.fields['attachment3'].label = "Attachment 3"
	    self.fields['reason'].label = "Purpose"
	    self.fields["employee"].queryset=Employee.objects.filter(dept=dept,is_active=True)

	class Meta:
   		model = Application
   		fields = ['employee', 'leave_type', 'date_from', 'date_to','reason','attachment1',
   		'attachment2','attachment3',]
   		widgets={'reason': Textarea(attrs={'cols': 10, 'rows': 5})}

	
	def is_valid(self):

		valid=super(ApplicationForm,self).is_valid()
		
		if not valid:
			return valid
	
		employee=self.cleaned_data['employee']
		date_from=self.cleaned_data['date_from']
		date_to=self.cleaned_data['date_to']
		leave_type=self.cleaned_data['leave_type']
	

		# if date_from<datetime.now().date():
		# 	self.errors['date_from']=['Invalid from date']
		# 	return False

		if(date_to<date_from):
			self.errors['date_to']=["Invalid to date"]

			return False

		
		

		if not employee.isLeaveLeft((date_to-date_from).days+1,leave_type):
			self.errors['date_to']=["Insufficient leave balance"]
			return False


		return True


class CreditApplicationForm(ModelForm):

	
	def __init__(self, dept,*args, **kwargs):
	    super(CreditApplicationForm, self).__init__(*args, **kwargs)
	    self.fields['attachment1'].label = "Attachment 1"
	    self.fields['attachment2'].label = "Attachment 2"
	    self.fields['attachment3'].label = "Attachment 3"
	    self.fields['days'].label="Number of days "
	    self.fields['reason'].label = "Purpose"
	    self.fields["employee"].queryset=Employee.objects.filter(dept=dept,is_active=True)
	    self.fields["is_credit"].initial=True



	class Meta:
   		model = Application
   		fields = ['employee', 'leave_type', 'is_credit' ,'days','reason','attachment1',
   		'attachment2','attachment3',]
   		widgets={'reason': Textarea(attrs={'cols': 10, 'rows': 5}),
   		'is_credit':forms.HiddenInput()}

	
	def is_valid(self):

		valid=super(CreditApplicationForm,self).is_valid()
		
		if not valid:
			return valid
		
		employee=self.cleaned_data['employee']
		days=self.cleaned_data['days']
		leave_type=self.cleaned_data['leave_type']
	
		if days<=0:
			self.errors['days']=["Please enter postive number of days"]
			return False


		return True


class CancelForm(forms.Form):

	def __init__(self,*args, **kwargs):
	    super(CancelForm, self).__init__(*args, **kwargs)
	    self.fields['attachment1'].label = "Attachment 1"
	    self.fields['attachment2'].label = "Attachment 2"
	    self.fields['attachment3'].label = "Attachment 3"
	reason=forms.CharField(widget=forms.Textarea)
	attachment1 = forms.FileField(required=False)
	attachment2 = forms.FileField(required=False)
	attachment3 = forms.FileField(required=False)

class SelectEmployeeForm(forms.Form):
    employee = forms.ModelChoiceField(queryset=Employee.objects.all(),label='')

    def __init__(self,dept,user_type,*args, **kwargs):
    	super(SelectEmployeeForm, self).__init__(*args, **kwargs)

    	employees=Employee.objects.all()
    	if user_type!=5:
    		self.fields['employee'].queryset=Employee.objects.filter(is_active=True)
    	if dept:
    		self.fields['employee'].queryset=Employee.objects.filter(dept=dept,is_active=True)
    
    	

       
  

class EmployeeEditForm(forms.Form):
	new_name = forms.CharField(max_length=100)
	new_dept = forms.ModelChoiceField(queryset=Department.objects.all())
	new_email = forms.EmailField(max_length=75)
	new_is_active= forms.BooleanField(initial=True,required=False)
	note=forms.CharField(max_length=200,widget=forms.Textarea(attrs={'size': '100'}))

	def __init__(self,*args, **kwargs):
		super(EmployeeEditForm, self).__init__(*args, **kwargs)
		self.fields['new_name'].label = "New Name"
		self.fields['new_dept'].label = "New Department"
		self.fields['new_email'].label = "New Email "
		self.fields['note'].label="Note to DR"
		

	"""
 	def save(self, commit=True):

   		if self.instance.pk is None:
   			fail_message='created'
   		else:
   			fail_message = 'changed'
   		exclude = ['earned_balance', 'hp_balance']
   		return save_instance(self, self.instance, self._meta.fields,
                             fail_message, commit, construct=False,
                             exclude=exclude)
	
	class Meta:
   		model = Employee
   		fields = ['code', 'name', 'dept', 'email','is_active',]	

	"""
   		
    	
    



class EmployeeNewForm(ModelForm):

	def __init__(self,*args, **kwargs):
	    super(EmployeeNewForm, self).__init__(*args, **kwargs)
	 
	  
 	def save(self, commit=True):

   		if self.instance.pk is None:
   			fail_message='created'
   		else:
   			fail_message = 'changed'
   		
   		return save_instance(self, self.instance, self._meta.fields,
                             fail_message, commit, construct=False,
                             )
	
	class Meta:
   		model = Employee
   		fields = ['code', 'name', 'dept','email',]	

leave/templates/leave/action_history.html
{% extends "leave/base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}


{% block container %}
<div class="row">
                <div class="col-md-12">
                    <h3>Action History</h3>
                    <ol class="breadcrumb">
                        <li>
                            <a href="{% url 'index' %}">Home</a>
                        </li>
                        <li class="active">Action History</li>
                    </ol>

                    <div class="pull-left">
                        {% if actions.has_other_pages %}
                        {% bootstrap_pagination actions %}
                        {% endif %}
                    </div>

                    <div class="pull-right">
                        <br>
                        <div class="btn-group">
                                <a class="btn btn-default {% if status == 6 %}active{% endif %}" href="{% url 'action_history' '' %}">All</a>
                                <a class="btn btn-default {% if status == 1 %}active{% endif %}" href="{% url 'action_history' 'pending' %}">Approval Pending</a>
                             
                                <a class="btn btn-default {% if status == 3 %}active{% endif %}" href="{% url 'action_history' 'approved' %}">Approved</a>
                                <a class="btn btn-default {% if status == 4 %}active{% endif %}" href="{% url 'action_history' 'rejected' %}">Rejected</a>
                      
                          
                        </div>
                    </div>
                    <div class="clearfix"></div>
 <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Generated Time</th>
                                <th>Action Type</th>
                                <th>Notes</th>
                                <th>Status</th>
                                <th>Action</th>
                            
                               
                            
                            </tr>
                        </thead>
                        <tbody>
                        
                        {% if actions %}
                            {% for action in actions %}
                            <tr>

                                <td>{{ forloop.counter0|add:actions.start_index}} </td>
                                <td>{{ action.time_generated }}</td>
                              
                                <td>{{ action.toText }}</td>
                                
                                <td>{{ action.note }}</td>
                                <td>{{ action.get_status_display }}</td>
                             
                                <td><a class="btn btn-default btn-xs" href="{% url 'action' action.pk %}"><i class="glyphicon glyphicon-stats"></i> &nbsp;View Details</a></td>
                            
                            </tr>
                            {% endfor %}

                        {% else %}
                        <tr><td colspan="8">No Actions yet.</td></tr>
                        {% endif %}
                        </tbody>
                    </table>
 


{% endblock container %}

{% block script %}
<script >
$(function(){
                $('#action_history').addClass('active');
            });
</script>
{% endblock script %}

leave/templates/leave/base.html
{% load bootstrap3 %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}LMS{% endblock title %}</title>

    <link href="{% static 'leave/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'leave/css/chosen.min.css' %}" rel="stylesheet">
    <link href="{% static 'leave/css/datepicker3.css' %}" rel="stylesheet">

    <script src="{% static 'leave/js/jquery-1.11.1.min.js' %}"></script>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
    .space-15px{
        height: 15px;
        margin:0;
        padding: 0;
        border: 0;
    }
    </style>
    {% block head %}
    {% endblock head %}
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Leave Management System</a>
        </div>
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
            {% if user_type == 1 %}
                <li id="new_leave"><a href="{% url 'new_application' '' %}">New Application</a></li>
                <li id="credit"><a href="{% url 'new_application' 'credit' %}">Credit Leave</a></li>
                <li id="history"><a href="{% url 'sent' '' %}">Application History</a></li>
                <li id="select_employee"><a href="{% url 'select_employee' %}">Employee Search</a></li>
            {% elif user_type == 2 %}
                <li id="applications"><a href="{% url 'applications' %}">Applications</a></li>
                <li id="select_employee"><a href="{% url 'select_employee' %}">Employee Search</a></li>
            {% elif user_type == 4 %}
                <li id="applications"><a href="{% url 'applications' %}">Applications</a></li>
                 <li id="actions"><a href="{% url 'actions' %}">Admin Actions</a></li>
                <li id="select_employee"><a href="{% url 'select_employee' %}">Employee Search</a></li>
       
            {% elif user_type == 5 %}
                <li id="employees"><a href="{% url 'employees' %}">Credit/Debit Leave</a></li>
                <li id="action_history"><a href="{% url 'action_history' %}">Action History</a></li>
                <li id="add_employee"><a href="{% url 'new_employee' %}">Add Employee</a></li>
                <li id="select_employee"><a href="{% url 'select_employee' %}">View/Edit Employee</a></li>
            {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li id="user_guide"><a href="{% url 'user_guide' %}">User Guide</a></li>
                 <li><a href="{% url 'logt' %}"><i class="glyphicon glyphicon-log-out"></i> Log out</a></li>
                 <!--
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{user.userprofile.get_user_type_display}} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="dropdown-header">{{user.first_name}}</li>
                        <li><a href="{% url 'logt' %}"><i class="glyphicon glyphicon-log-out"></i> Log out</a></li>
                    </ul>
                </li>
                -->
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block container %}
        {% endblock container %}
    </div>
    <div class="space-15px"></div>
    <script src="{% static 'leave/js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'leave/js/chosen.jquery.min.js' %}" ></script>
    <script src="{% static 'leave/js/bootstrap-datepicker.js' %}" ></script>
    {% block script %}
    {% endblock script %}
    
</body>
</html>

leave/templates/leave/new_application.html
{% extends "leave/base.html" %}
{% load bootstrap3 %}

{% block container %}
<div class="row">
    <div class="col-md-12">
        <h3>Create Application - {% if is_credit %}
            Credit Leave
        {% else %}
            New Leave
        {% endif %}
        </h3>

        <ol class="breadcrumb">
            <li>
                <a href="{% url 'index' %}">Home</a>
            </li>
            <li class="active">{% if is_credit %}
                Credit Leave
            {% else %}
                New Leave
            {% endif %}</li>
        </ol>
        <p>Please fill the details for the application. You can add upto 3 attachments if required.</p>
        <form role="form" action="   {% if is_credit %}
            {% url 'new_application' 'credit' %}
        {% else %}
            {% url 'new_application' 'debit' %}
        {% endif %}"
        method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="row">
            <div class="col-md-6">
                {% if is_credit %}
                    {% bootstrap_field form.is_credit %}
                {% endif %}
                {% bootstrap_field form.employee %}
                {% bootstrap_field form.leave_type %}
                {% bootstrap_field form.reason %}
            </div>
            <div class="col-md-6">
                {% if is_credit %}
                    {% bootstrap_field form.days %}
                {% else %}
                    {% bootstrap_field form.date_from %}
                    {% bootstrap_field form.date_to %}
                    
                {% endif %}
                {% bootstrap_field form.attachment1 %}
                {% bootstrap_field form.attachment2 %}
                {% bootstrap_field form.attachment3 %}
                <br>
                <button class="btn btn-default" type="button" id="add-attachment"><i class="glyphicon glyphicon-plus"></i> Add Attachment</button>
            </div>
        </div>
        
        <button type="submit" class="btn btn-success btn-lg"><i class="glyphicon glyphicon-chevron-right"></i> Create Application </button>
    </form>
</div>
</div>
{% endblock container %}

    {% block script %}
    <script>
            $(function() {

                $('#id_leave_type, #id_employee').chosen({
                    disable_search_threshold: 2,
                });

                $('#id_date_from, #id_date_to').attr('readonly', true).css({
                    backgroundColor: '#ffffff',
                    cursor: 'pointer',
                });

                $('#id_date_from, #id_date_to').datepicker({
                    todayHighlight: true
                });

                $('#id_attachment1, #id_attachment2, #id_attachment3').parents('.form-group').hide();

                if($('#id_attachment1').parents('.form-group').hasClass('has-error')){
                    $('#id_attachment1').parents('.form-group').show();
                }

                if($('#id_attachment2').parents('.form-group').hasClass('has-error')){
                    $('#id_attachment1, #id_attachment2').parents('.form-group').show();
                }

                if($('#id_attachment3').parents('.form-group').hasClass('has-error')){
                    $('#id_attachment1, #id_attachment2, #id_attachment3').parents('.form-group').show();

                    $('#add-attachment').hide();
                }


                $('#add-attachment').on('click', function(event){
                    event.preventDefault();

                    if(!$('#id_attachment1').is(':visible')){
                        $('#id_attachment1').parents('.form-group').show();
                    }else if(!$('#id_attachment2').is(':visible'))
                        $('#id_attachment2').parents('.form-group').show();
                    else{
                        $('#id_attachment3').parents('.form-group').show();
                        $('#add-attachment').hide();
                    }
                });

            });
            $(function(){
                {% if is_credit %}
                    $('#credit').addClass('active');
                {% else %}
                    $('#new_leave').addClass('active');
                {% endif %}
                
                });
        </script>
      

   {% endblock script %}

leave/templates/leave/select_employee.html
{% extends "leave/base.html" %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block title %}LMS - Employee Search {% endblock title %}
{% block container %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h3>Select an Employee</h3>
            <form action="{% url 'select_employee' %}" method="POST" >
                {% csrf_token %}
                {% bootstrap_field form.employee %}
                <br><button type="submit" class="btn btn-info btn-lg btn-block"><i class="glyphicon glyphicon-stats"></i> {% if user_type == 5 %} View/Edit Employee {% else %} View Details {% endif %} </button>
            </form>
            
        </div>
    </div>
{% endblock container %}

{% block script %}
<script>  
$('#id_employee').chosen({
                    disable_search_threshold: 5,
                });
$(function(){
    $('#select_employee').addClass('active')
});
</script>  
{% endblock script %}